run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  govet:
    enable-all: true
    disable:
      - fieldalignment
    settings:
      shadow:
        strict: true

  gocyclo:
    min-complexity: 10

  dupl:
    threshold: 80

  goconst:
    min-len: 2
    min-occurrences: 2
    numbers: true

  misspell:
    locale: US
    ignore-words:
      - cancelled

  lll:
    line-length: 100
    tab-width: 1

  goimports:
    local-prefixes: github.com/tg123/sshpiper

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - unnamedResult
      - paramTypeCombine
      - hugeParam
      - rangeValCopy

  funlen:
    lines: 50
    statements: 30
    ignore-comments: true

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G106  # ssh InsecureIgnoreHostKey
      - G301  # directory permissions
      - G304  # file inclusion via variable

  cyclop:
    max-complexity: 10
    package-average: 8

  nestif:
    min-complexity: 3

  gofumpt:
    extra-rules: true

  revive:
    severity: error
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: constant-logical-expr
      - name: bool-literal-in-expr
      - name: flag-parameter
      - name: unnecessary-stmt
      - name: struct-tag
      - name: modifies-parameter
      - name: confusing-naming
      - name: get-return
      - name: deep-exit
      - name: unused-receiver
      - name: identical-branches
      - name: defer

  gomodguard:
    blocked:
      modules:
        - github.com/golang/protobuf:
            recommendations:
              - google.golang.org/protobuf
            reason: "use the new protobuf module"
        - github.com/pkg/errors:
            recommendations:
              - errors
              - fmt
            reason: "use standard library errors"

  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax
        files:
          - $all
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages"
          - pkg: github.com/pkg/errors
            desc: "use standard library errors instead"

  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
        xml: camel
        bson: camel
        avro: snake
        mapstructure: kebab

  varnamelen:
    min-name-length: 3
    ignore-names:
      - err
      - id
      - ip
      - ok
      - w
      - r
      - i
      - j
      - k
      - v
    ignore-decls:
      - c echo.Context
      - t testing.T
      - f *os.File
      - i int
      - w http.ResponseWriter
      - r *http.Request

  wsl:
    strict-append: true
    allow-assign-and-call: false
    allow-multiline-assign: false
    allow-cuddle-declarations: false
    allow-trailing-comment: false
    force-case-trailing-whitespace: 0
    force-err-cuddling: true
    allow-separated-leading-comment: false

  nlreturn:
    block-size: 2

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/tg123/sshpiper)
    skip-generated: true
    custom-order: true

  whitespace:
    multi-if: true
    multi-func: true

  testifylint:
    enable-all: true

  perfsprint:
    err-error: true
    errorf: true
    sprintf1: true
    int-conversion: true

  interfacebloat:
    max: 5

  inamedparam:
    skip-single-param: true

  grouper:
    const-require-single-const: true
    const-require-grouping: true
    import-require-single-import: false
    import-require-grouping: true
    type-require-single-type: true
    type-require-grouping: true
    var-require-single-var: true
    var-require-grouping: true

linters:
  enable:
    # Error detection
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - nilerr
    - noctx
    - wastedassign
    - exhaustive
    - exhaustruct

    # Style
    - decorder
    - gci
    - gofmt
    - gofumpt
    - goimports
    - revive
    - unconvert
    - unparam
    - whitespace
    - wsl
    - grouper

    # Complexity
    - cyclop
    - dupl
    - funlen
    - gocognit
    - gocyclo
    - nestif
    - gocyclo

    # Performance
    - gocritic
    - prealloc
    - perfsprint

    # Bugs
    - asciicheck
    - bidichk
    - exportloopref
    - copyloopvar
    - goconst
    - gochecknoinits
    - gochecknoglobals
    - gosimple
    - misspell
    - nolintlint
    - predeclared
    - reassign
    - testableexamples
    - tenv
    - testifylint
    - usestdlibvars
    - interfacebloat
    - inamedparam

    # Format
    - lll
    - nlreturn
    - tagliatelle
    - varnamelen

    # Import
    - depguard
    - gomodguard

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: ""
  fix: false

severity:
  default-severity: error
  rules:
    - linters:
        - dupl
        - goconst
      severity: warning
    - linters:
        - lll
      severity: info