run:
  timeout: 5m
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable:
      - shadow
    settings:
      shadow:
        strict: true

  gocyclo:
    min-complexity: 10

  dupl:
    threshold: 80

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true

  misspell:
    locale: US

  lll:
    line-length: 120
    tab-width: 1

  goimports:
    local-prefixes: github.com/tg123/sshpiper

  funlen:
    lines: 80
    statements: 40
    ignore-comments: true

  gosec:
    severity: medium
    confidence: medium

  cyclop:
    max-complexity: 10
    package-average: 8

  nestif:
    min-complexity: 4

  varnamelen:
    min-name-length: 2
    ignore-names:
      - err
      - id
      - ip
      - ok
      - w
      - r
      - i
      - j
      - k
      - v
      - to
    ignore-decls:
      - c echo.Context
      - t testing.T
      - f *os.File
      - w http.ResponseWriter
      - r *http.Request

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - goconst
    - misspell
    - gofmt
    - goimports
    - dupl
    - cyclop
    - funlen
    - nestif
    - varnamelen
  disable:
    - depguard

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "G304"
    - linters:
        - gosec
      text: "G204"
    - linters:
        - varnamelen
      path: "_test\\.go"
    - path: "crypto/"
      linters:
        - gosec
        - goconst
        - funlen

  max-issues-per-linter: 50
  max-same-issues: 10
  new-from-rev: ""
  fix: false

severity:
  default-severity: error
